version: '3'

services:
    hcis:
        container_name: hcis
        image: hcis
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --port 8080 --host 0.0.0.0'
        ports:
            - "8080:8080"
