version: '3'

services:
    hcis:
        container_name: hcis
        image: hcis
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - "../:/var/www/"
